### ISSUE TITLE
Recover account doesn't work

### ISSUE THREAD

**Issue by xlc** [stylo-app/stylo#10]
Using v0.9.5, trying to import account from Parity Signer but cannot get the final create button enabled. Can't tell what's missing or if I enter the phase wrong.

**Comment by Tbaut** [comment]
Hey Brian, thanks for the report. Are you 100% certain that there is no typo? To be sure, make sure to only use the suggested words. If the seed isn't correct, the input field will remain red. If it's correct it'll turn green and show you the account.

I have triple checked on my side and was able to recover an account.

**Comment by xlc** [comment]
Yeah I entered 24 * abacus using the suggest words and still red box.
A minor feature request, it will be useful to display number of words entered like `23/24`

**Comment by Tbaut** [comment]
But 24x abacus is not a valid BIP39 mnemonic. There is no way Parity Signer ever gave you such a phrase. Try with a real BIP39 like the ones you get with Parity Signer or https://iancoleman.io/bip39/ and you'll see that it's working as expected.

**Comment by xlc** [comment]
ok. I guess I had a typo somewhere on my first try.
