### ISSUE TITLE
Astar signing got an error Unable to parse QR data. Any idea how to resolve this issue?

### ISSUE THREAD

**Issue by ccfiel** [stylo-app/stylo#18]
![20220118_175654](https://user-images.githubusercontent.com/1788360/149915364-8b8ac0f2-0a42-4625-8f57-593b9983674d.jpg)

**Comment by ccfiel** [comment]
hello @Tbaut I used the latest stylo-v0.9.9.apk

**Comment by Tbaut** [comment]
Understood, then if you didn't add Astar yourself (which is not supported by v0.9.9) then it won't work indeed. Unless Parity Signer is not released in the next 2 weeks, I will add it.

**Comment by ccfiel** [comment]
@Tbaut I did not add myself I just tried to to select the polkadot account :) Maybe I can try to add it? I did tried to look at the code. I need to add the genesisHash. Where do I get that info in astar?

**Comment by ccfiel** [comment]
or just wait for 2 weeks? :) @Tbaut

**Comment by Tbaut** [comment]
it's a little more than just the genesis hash, here is a commit where I added Acala. It needs logos, metadata, and several other info that you can find on Polkadot.js/apps. https://github.com/stylo-app/stylo/commit/c54cb3881feb24f7adf67f8f66bc5a7a341b1349

**Comment by ccfiel** [comment]
@Tbaut  is this the genesis hast of astar? https://astar.subscan.io/block/0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6 did I get it right? :)

**Comment by SvenMeyer** [comment]
@Tbaut , So the Parity Signer will finally be released "soon" and will be more secure than Stylo ?

**Comment by Tbaut** [comment]
Party Signer v5 will have a way to upgrade and add networks. This is a major change, and will allow the offline signer to evolve without having to install new version manually. Regarding the security, it has a lot of changes in the code, which hasn't really been proven yet, this is the main issue. I can't judge regarding the security as of now.

**Comment by ccfiel** [comment]
https://github.com/stylo-app/stylo/issues/21 it is now added.
