### ISSUE TITLE
Build and deploy Stylo on iOS

### ISSUE THREAD

**Issue by Tbaut** [stylo-app/stylo#2]
We need stylo on iOS :)

**Comment by Tbaut** [comment]
I will not be able to do this in the near term unfortunately, by lack of time and dedication. I want to focus on Android that allows to keep a phone truly offline, while allowing to upgrade Stylo with sd cards.

**Comment by FartFeatures** [comment]
Can we reopen this, I've started work on getting it to build.

**Comment by Tbaut** [comment]
Hey @FartFeatures thanks a lot for taking this on, this is awesome. The best way to go forward with this is actually to fork the repo and use the code to build and publish an app on iOS.

Unfortunately, since I do not have the time and hardware to test and vouch for what will be published on Apple store, you would have to use another brand and logo.
