### ISSUE TITLE
9.10 still does have astra and when look at the about menu still the version number is 0.9.9-beta

### ISSUE THREAD

**Issue by ccfiel** [stylo-app/stylo#21]
@Tbaut I did try to uninstall and install again still the same, tried also clear cache, clear data still the same. Any idea why?

**Comment by Tbaut** [comment]
Hi, do you install it using the play store? Because this one is not up to date and still has an earlier version. Also Stylo is not meant to be used on an online phone... So I encourage you to download the apk, and keep Stylo on a phone that has been factory reset, and is kept offline **at all time**.

**Comment by ccfiel** [comment]
@Tbaut I am downloading in release  https://github.com/stylo-app/stylo/releases/tag/v0.9.10 not in the play store

**Comment by Tbaut** [comment]
Thanks for confirming, let me try it, I will get back to you shortly.

**Comment by Tbaut** [comment]
The build failed silently, there are some incompatibility with `@polkadot/util-crypto` that got bumped, I'll revert this and publish again. Sorry for the trouble.

**Comment by ccfiel** [comment]
@Tbaut no worries :) glad to help with this project :)

**Comment by Tbaut** [comment]
for the record, I'm hitting an issue I don't understand probably related to some recent package changes, seeking help here https://github.com/polkadot-js/common/issues/1384

**Comment by Tbaut** [comment]
I've had a hard time understanding why.. but I managed to build v0.9.10, and it's showing as such on my device now. Can you give it a try https://github.com/stylo-app/stylo/releases/tag/v0.9.10 ?

**Comment by ccfiel** [comment]
@Tbaut I did have now astar in the option. My problem is how to add my existing account? I tried to create a new account with Astar it create a new different wallet. When I join crownloan I use my polkadot wallet. I did add my polkadot wallet in https://polkadot.js.org/apps/ using Add via QR. I did see my wallet balance. My question is how to access the astar wallet base on my polkadot wallet?

**Comment by ccfiel** [comment]
@Tbaut I was able to sign. I just need the right derivative path :) thanks! more power! :)
