### ISSUE TITLE
Instructions for sideloading apk to devices

### ISSUE THREAD

**Issue by hitchhooker** [stylo-app/stylo#23]
Seems like up to date version are not anymore published on Google Play store, so instructions for installing wallet to offline device could be good idea. Downloading from app store is not necessarily problem though if you are running Pixel phone with GrapheneOS(hardened android) as a operating system and have setup Stylo's Network permissions of meaning it is completely isolated from rest of the OS.

**Comment by hitchhooker** [comment]
## Requirements

### Enable USB debugging on your Android offline device
Settings > System > About phone >  Software Information > and click 5 times Build number.
Enter Deverloper settings and enable USB Debugging.

### Install dependencies 
On Arch Linux:
```
sudo pacman -S android-udev curl jq
```
On Debian and Ubuntu:
```
sudo apt install android-sdk-platform-tools-common curl jq 
```
On MacOS:
Install CLI tools https://developer.android.com/studio
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
brew install jq
```

If your operating system doesn't include a usable version of adb, you can use the official standalone releases of platform-tools. This is our recommendation for most users. The flashing process won't work unless you follow these instructions including setting up PATH.

To download, verify and extract the standalone platform-tools on Debian and Ubuntu:
```
sudo apt install libarchive-tools
curl -O https://dl.google.com/android/repository/platform-tools_r31.0.3-linux.zip
echo 'e6cb61b92b5669ed6fd9645fad836d8f888321cd3098b75588a54679c204b7dc  platform-tools_r31.0.3-linux.zip' | sha256sum -c
bsdtar xvf platform-tools_r31.0.3-linux.zip
```
To download, verify and extract the standalone platform-tools on macOS:
```
curl -O https://dl.google.com/android/repository/e8b2b4cbe47c728c1e54c5f524440b52d4e1a33c.platform-tools_r31.0.3-darwin.zip
echo 'SHA256 (e8b2b4cbe47c728c1e54c5f524440b52d4e1a33c.platform-tools_r31.0.3-darwin.zip) = 773c08cfa31cec1bb4568ce5b374366e6310a5ffc21875024604a0f65bc831b1' | shasum -c
tar xvf e8b2b4cbe47c728c1e54c5f524440b52d4e1a33c.platform-tools_r31.0.3-darwin.zip
```
To download, verify and extract the standalone platform-tools on Windows:
```
curl -O https://dl.google.com/android/repository/platform-tools_r31.0.3-windows.zip
(Get-FileHash platform-tools_r31.0.3-windows.zip).hash -eq "0f4b8fdd26af2c3733539d6eebb3c2ed499ea1d4bb1f4e0ecc2d6016961a6e24"
tar xvf platform-tools_r31.0.3-windows.zip
```
Next, add the tools to your PATH in the current shell so they can be used without referencing them by file path, enabling usage by the flashing script.

On Debian, Ubuntu and macOS:
```
export PATH="$PWD/platform-tools:$PATH"
```
On Windows:
```
$env:Path = "$pwd\platform-tools;$env:Path"
```
This only changes PATH for the current shell and will need to be done again if you open a new terminal.


```
curl -s https://api.github.com/repos/stylo-app/stylo/releases/latest | jq -r '.assets[] | .browser_download_url' | xargs curl -L -o stylo.apk
```
Turn off the internet connection of the device before plugging USB cable to the PC.
```
adb install -r stylo.apk
```

**Comment by hitchhooker** [comment]
Truth is that this is all still technically demanding and we should consider making easier website form for installing and look into possibility of browser based offline installer(like https://grapheneos.org/install/web) as fucked up it sounds for offline wallet. I could imagine there is possibility to download the apk in browser memory, but aint sure. 
another point that comes in mind it would be good to recommend phone models that are supported by [Attestation app](https://attestation.app/about) for wallet usage, to have certainty that boot was verified before the first installation of stylo.

**Comment by hitchhooker** [comment]
could you start adding sha256 checksums as stylo.apk.sig in releases, so we could use your public key with signify for authenticating signatures in apk's easier or how is the checksum check supposed to be done right now?
```
signify -Cqp stylo.pub -x stylo.apk.sig && echo 'Stylo.apk signature verified'
```

**Comment by Tbaut** [comment]
Adding any kind of connectivity to the mobile device, connecting it to an online device, or let alone allowing developer settings is opening the attack surface. Right now, the main threat is if the device has been rooted/infected probably through a physical access. Even if I am hacked or I'm myself malicious, and some malicious code is included in the app, the fact that the mobile remains offline, no information can be extracted as long as it remains offline.
