### ISSUE TITLE
Acala metadata is out of date.

### ISSUE THREAD

**Issue by Zerophase** [stylo-app/stylo#24]
Acala just updated their metadata to enable liquidity pools. They have a bootstrap program running currently. Is there any means of updating this for the app?

**Comment by ccfiel** [comment]
@Tbaut I did create a PR for updated acala metadata. https://github.com/stylo-app/stylo/pull/25

**Comment by Tbaut** [comment]
Thanks, note that I cannot create and push update for every single Metadata update. If you are really in hurry, and trust that you are not on a pishing website, nor using a malicious extension, you do not have to wait and can still Yolo sign at your own risks as long as the network is supported (Acala is already).
I push updates with as many Metadata update as possible in order not have to update every couple days. I will push one later today or tomorrow, with all the networks updated.

Cheers

**Comment by Tbaut** [comment]
Fixed as part of https://github.com/stylo-app/stylo/releases/tag/v0.9.12

**Comment by Zerophase** [comment]
> Thanks, note that I cannot create and push update for every single Metadata update. If you are really in hurry, and trust that you are not on a pishing website, nor using a malicious extension, you do not have to wait and can still Yolo sign at your own risks as long as the network is supported (Acala is already). I push updates with as many Metadata update as possible in order not have to update every couple days. I will push one later today or tomorrow, with all the networks updated.
> 
> Cheers

Metadata never impacts whether money makes it there on a legitimate site?
