### ISSUE TITLE
Does Stylo use https://polkadot.js.org/phishing/# to block the addresses involved in the scam?

### ISSUE THREAD

**Issue by ccris02** [stylo-app/stylo#26]
Does Stylo use https://polkadot.js.org/phishing/# to block the addresses involved in the scam?
Based on the polkadot{.js}/phishing addresses are only blocked by [polkadot{.js} apps](https://polkadot.js.org/apps) and [Fearless Wallet](https://fearlesswallet.io/).
"The addresses are blocked in wallets such as polkadot{.js} apps and Fearless Wallet."
Would we be able to integrate address blocking in Stylo?

**Comment by Tbaut** [comment]
The answer is the same as for Parity Signer. Stylo is an offline wallet and can only work together with an online part. Stylo works with Polkadot.js extension, hence the extension does the job of checking beforehand.
