### ISSUE TITLE
 v0.9.13 does not work with Acala

### ISSUE THREAD

**Issue by darko-mijic** [stylo-app/stylo#31]
Hello,

I've tried [the latest  v0.9.13 release](https://github.com/stylo-app/stylo/releases/tag/v0.9.13) and it does not work with Acala.

I am getting this error for every transaction I've tried:

```
incentives: claimRewards
1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
```

There is enough funds for fees.

**Comment by Tbaut** [comment]
This is not a Stylo error and if the interface tells you there's not enough for fees, I'm pretty sure it means there's not enough for fees indeed! If your balance is not claimed, are you sure your transferable balance is not 0? I'll try it out nevertheless in the next days.

**Comment by Tbaut** [comment]
Just tested and it works as expected. You must be trying to send more than you have.

**Comment by darko-mijic** [comment]
It does work. Sorry for the false alarm, it was a mistake on my end. 
Thank you for maintaining this very important project!
