### ISSUE TITLE
Can we please add Efinity 

### ISSUE THREAD

**Issue by ccfiel** [stylo-app/stylo#34]
@Tbaut Can we please add Efinity?

**Comment by Tbaut** [comment]
Thanks for the request. As I wrote elsewhere, https://github.com/stylo-app/stylo/issues/30#issuecomment-1133606009 since Parity Signer v5 has been released for Android, I stopped stop adding networks, because this way of doing (manually adding them) is not scalable. Stylo was meant to replace Signer v4, because at the time, Signer was not in a good shape. Now that the team has released an improved version I will only provide minimal maintenance for existing networks and rather concentrate my efforts on making Signer better. Thanks for your understanding.

**Comment by ccfiel** [comment]
@Tbaut I tried to use the new parity signer it's not ready yet only 3 network support. Hope you can efinity.

**Comment by Tbaut** [comment]
It's definitely ready, you can add networks yourself by scanning QR codes. It's not perfect for sure, but it support any substrate network, as long as they are added. I documented very briefly a step by step to build and add networks here https://github.com/paritytech/parity-signer/issues/950#issue-1168996169

I plan to host a metadata upgrade portal myself to help users out with unsigned metadata.. soon. I'll try to remember to comment here once it's live.

**Comment by ccfiel** [comment]
Thanks! 😊

**Comment by ccfiel** [comment]
Hello, @Tbaut I thought the new parity signer has the ability to add a network by just scanning the QR Code. I did try to scan the Efinity QR code using this site https://nova-wallet.github.io/metadata-portal/#/efinity but after scanning I got this error. Any idea why?

![Screenshot_20220808-173242_Parity_Signer](https://user-images.githubusercontent.com/1788360/183388776-f8c8f05d-85ac-4c34-a7ad-f18a7f7d450c.jpg)

**Comment by Tbaut** [comment]
I do not intend to be the support person for all the projects out there. Please open issues in the relevent github repo next time :)

What this says is that you must add the chain spec first.

**Comment by ccfiel** [comment]
@Tbaut ok thanks! so it should be added to the app first and they have to release a new app same concept as stylo. I think it does not do any better than what you have done. So I think it's not ready yet :)

**Comment by Tbaut** [comment]
Nope, you need to scan the qr code with the network spec first, then scan the qr code for the Metadata.

**Comment by ccfiel** [comment]
@Tbaut I already did that but still got an error.  Just making a point here stylo still better. :) 

![ksnip_20220808-180737](https://user-images.githubusercontent.com/1788360/183394605-2c18879e-461a-4254-b41f-a65d89c4f17c.png)

![Screenshot_20220808-180704_Parity_Signer](https://user-images.githubusercontent.com/1788360/183394695-2e6a0baf-d3cb-400c-a6da-3217080c2ea8.jpg)

**Comment by Tbaut** [comment]
Ah now you hit an error related to the Metadata portal I think, where the nova team (providing the Metadata portal you used) could certainly help. I agree that the UX is not ideal, but this brings so much more added security and scalability to the process. Stylo was a much needed patch, useful for some time, but relying on the opsec of one person, myself, is not sustainable for a security oriented application.
