### ISSUE TITLE
Interlay transactions don't work.

### ISSUE THREAD

**Issue by Zerophase** [stylo-app/stylo#36]
When you try to scan a transaction QR code you get an error message for Interlay. Happens when staking and trying to transfer to Acala.

**Comment by Tbaut** [comment]
Thanks for the report. May I ask what's the error message?

**Comment by Zerophase** [comment]
Unable to parse QR data. Something went wrong decoding the Substrate UOS payload.

**Comment by Tbaut** [comment]
I had a closer look and found many issues around Interlay that I hadn't updated in a while. Please try the v0.9.15 release https://github.com/stylo-app/stylo/releases/tag/v0.9.15 (not published on the store) and let me know if there's any issue.

**Comment by Zerophase** [comment]
When I click on an account I get an updating loop forever. Can't change the blockchain anymore.

**Comment by Tbaut** [comment]
I forgot to fix the recovery part, it should be good according to my tests in v0.9.16. Please make sure to update Stylo according to the best practice (bo hot update, you must uninstall stylo before reinstalling it)
