### ISSUE TITLE
Continue/confirm support for Ethereum chains

### ISSUE THREAD

**Issue by SvenMeyer** [stylo-app/stylo#40]
I really like the QR-code scanning approach, not forcing users to buy a hardware wallet (with its own issues).
From the README it looks like as if Parity Signer v5 suppose to support Ethereum chains, but I can find any reference to it on their page.
Although, neither Metamask, Talisman, Frame not (yet) support signing txs via QR-code (I already sent messages / created tickets to all of them) it would be great to have at least a working and supported signer.

Or did I miss anything ?

**Comment by Tbaut** [comment]
There are wallets out there supporting ethereum signing. Note that the standard used by Metamask is not compatible with what was used on signer. 

Things have moved though, Metamask support a qr bases wallet called keystone that I recommend to check out. https://support.keyst.one/3rd-party-wallets/eth-and-web3-wallets-keystone/bind-metamask-with-keystone/how-to-use-metamask-keystone-with-defi

For the mobile approach, you may check out some other app, the one that comes to mind is callers airgap. https://support.airgap.it/guides/metamask/

**Comment by SvenMeyer** [comment]
@Tbaut Thanks for the feedback !
although I found the idea to use an existing ("old") phone quite interesting, the keystone one looks like what I had in mind. Apparently, they have some Metamask Add-on that I can sign with a QR-code (too bad MM does not have that out of the box).
One I have that add-on installed, would I be able to sign with stylo or Parity Signer as well ?

**Comment by Tbaut** [comment]
I can't vouch for it as I have never used it, you have to do your own research. Stylo is not actively maintained any more, see https://github.com/stylo-app/stylo#readme so I just point to other existing solutions.
